[tool.poetry]
name = "poetryfastpandendic"
version = "0.1.0"
description = "everything that I would need"
authors = ["Damian <damczys@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
